#12 edit process

diff --git a/index-export b/index-export
--- a/index-export
+++ b/index-export
@@ -95,68 +95,81 @@ if [ "$snapshot" == "" ]; then
     snapshot="snapshot_$index"
 fi
 
-# clean folder
+# remove existing repository
 if [ $from_step -le 1 ]; then
-    echo "[Step 1] Remove snapshot files at snapshot repository."
+    echo "[Step 1] Check if the repository '$repo' is registered."
+    curl --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo"
+
+    if [ $? -eq 0 ]; then
+        echo
+        echo "[Step 1] Repository has already registered. Unregister it."
+        curl -X DELETE --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo"
+        if [ $? -eq 0 ]; then
+            echo
+            echo "[Step 1] Unregister succeed."
+        else
+            echo
+            echo "[Step 1] Unregister failed."
+            exit 1
+        fi
+    else
+        echo
+        echo "[Step 1] Repository hasn't registered."
+    fi
+fi
+
+# clean folder
+if [ $from_step -le 2 ]; then
+    echo "[Step 2] Remove snapshot files at snapshot repository."
     docker exec -i $es_container rm -rf "$register_path"
     docker exec -i $es_container mkdir "$register_path"
     docker exec -i $es_container chown -R elasticsearch:root "$register_path"
 fi
 
 # checking repository register
-if [ $from_step -le 2 ]; then
-    echo "[Step 2] Check if the repository '$repo' is registered."
-    curl --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo"
-
+if [ $from_step -le 3 ]; then
+    curl --fail-with-body -X PUT "http://$es_host:$es_port/_snapshot/$repo" \
+        -H "Content-Type: application/json" \
+        -d "{\"type\":\"fs\",\"settings\":{\"location\":\"$register_path\"}}"
+    
     if [ $? -eq 0 ]; then
         echo
-        echo "[Step 2] Repository has already registered."
+        echo "[Step 3] Register succeed."
     else
         echo
-        echo "[Step 2] Repository isn't registered. Start registering with path '$register_path'"
-        curl --fail-with-body -X PUT "http://$es_host:$es_port/_snapshot/$repo" \
-            -H "Content-Type: application/json" \
-            -d "{\"type\":\"fs\",\"settings\":{\"location\":\"$register_path\"}}"
-        
-        if [ $? -eq 0 ]; then
-            echo
-            echo "[Step 2] Register succeed."
-        else
-            echo
-            echo "[Step 2] Register failed."
-            exit 1
-        fi
+        echo "[Step 3] Register failed. You can retry from this step with option '--from-step 3'."
+        exit 1
     fi
 fi
 
 # Check if snapshot exists
-if [ $from_step -le 3 ]; then
-    echo "[Step 3] Check if snapshot '$snapshot' exists."
+if [ $from_step -le 4 ]; then
+    echo "[Step 4] Check if snapshot '$snapshot' exists."
     curl --silent --fail "http://$es_host:$es_port/_snapshot/$repo/$snapshot" > /dev/null
 
     if [ $? -eq 0 ]; then
-        echo "[Step 3] Snapshot '$snapshot' exists. Start deleting."
+        echo "[Step 4] Snapshot '$snapshot' exists. Start deleting."
         curl --fail-with-body -X DELETE "http://$es_host:$es_port/_snapshot/$repo/$snapshot"
 
         if [ $? -ne 0 ]; then
-            echo "[Step 3] delete failed. You can retry from this step with option '--from-step 3'."
+            echo "[Step 4] delete failed. You can retry from this step with option '--from-step 4'."
             exit 1
         fi
     else
-        echo "[Step 3] Snapshot '$snapshot' doesn't exist."
+        echo "[Step 4] Snapshot '$snapshot' doesn't exist."
     fi
 fi
 
 # creating snapshot
-if [ $from_step -le 4 ]; then
+if [ $from_step -le 5 ]; then
     if [ "$index" == "" ]; then
         echo
-        echo "[Step 4] Start creating snapshot."
+        echo "[Step 5] Start creating snapshot."
         curl --fail-with-body -X PUT "http://$es_host:$es_port/_snapshot/$repo/$snapshot?wait_for_completion=true" \
             -H "Content-Type: application/json"
     else
         echo
-        echo "[Step 4] Start creating snapshot with index '$index'"
+        echo "[Step 5] Start creating snapshot with index '$index'"
 
         curl --fail-with-body -X PUT "http://$es_host:$es_port/_snapshot/$repo/$snapshot?wait_for_completion=true" \
             -H "Content-Type: application/json" \
@@ -165,38 +178,38 @@ if [ $from_step -le 4 ]; then
 
     if [ $? -eq 0 ]; then
         echo
-        echo "[Step 4] Creating snapshot succeed."
+        echo "[Step 5] Creating snapshot succeed."
     else
         echo
-        echo "[Step 4] Creating snapshot failed. You can retry from this step with option '--from-step 4'."
+        echo "[Step 5] Creating snapshot failed. You can retry from this step with option '--from-step 5'."
         exit 1
     fi
 fi
 
 # unregister
-if [ $from_step -le 5 ]; then
-    echo "[Step 5] Unregister repository."
+if [ $from_step -le 6 ]; then
+    echo "[Step 6] Unregister repository."
     curl --fail-with-body -X DELETE "http://$es_host:$es_port/_snapshot/$repo"
 
     if [ $? -ne 0 ]; then
         echo
-        echo "[Step 5] Unregister failed. You can retry from this step with option '--from-step 5'."
+        echo "[Step 6] Unregister failed. You can retry from this step with option '--from-step 6'."
         exit 1
     fi
 fi
 
 # Copy from docker container
-if [ $from_step -le 6 ]; then
+if [ $from_step -le 7 ]; then
     if [ "$output" == "" ]; then
         output="backup_$index"
     fi
 
     echo
-    echo "[Step 6] Copy folder '$register_path' from docker continer '$es_container' to '$output'"
+    echo "[Step 7] Copy folder '$register_path' from docker continer '$es_container' to '$output'"
     docker cp $es_container:$register_path ./$output
 
     if [ $? -ne 0 ]; then
-        echo "[Step 6] copied failed. You can retry from this step with option '--from-step 6'."
+        echo "[Step 7] copied failed. You can retry from this step with option '--from-step 7'."
         exit 1
     fi
 fi
