#3 add step option

diff --git a/index-import b/index-import
--- a/index-import
+++ b/index-import
@@ -5,6 +5,7 @@ es_host=127.0.0.1
 es_port=9200
 es_container=elasticsearch
 register_path="/usr/share/elasticsearch/backup"
+from_step=0
 
 while (($#)); do
     case $1 in
@@ -48,6 +49,11 @@ while (($#)); do
             target=$1
             shift
         ;;
+        "--from-step" | "-f")
+            shift
+            from_step=$1
+            shift
+        ;;
         "--help" | "-h")
             echo "Required options:"
             echo "    --snapshot <snapshot>, -s <snapshot>"
@@ -68,6 +74,8 @@ while (($#)); do
             echo "        Index that specified to be imported. Defaultly import all indices."
             echo "    --register-path <path>, -rp <path>"
             echo "        Path of snapshot repository. Used for registering repository if repository doesn't exists. Default: /usr/share/elasticsearch/backup"
+            echo "    --from-step <step>, -f <step>"
+            echo "        Start from which step. Default: 1"
             exit 0
         ;;
         *)
@@ -92,132 +100,150 @@ if [ "$target" == "" ]; then
     exit 1
 fi
 
-# checking repository register
-echo "Check if the repository '$repo' is registered."
-curl --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo"
-
-if [ $? -eq 0 ]; then
-    echo
-    echo "Repository has already registered."
-else
-    echo
-    echo "Repository isn't registered. Start registering with path '$register_path'"
-    curl --fail-with-body -X PUT "http://$es_host:$es_port/_snapshot/$repo" \
-        -H "Content-Type: application/json" \
-        -d "{\"type\":\"fs\",\"settings\":{\"location\":\"$register_path\"}}"
+# Step 1: checking repository register
+if [ $from_step -le 1 ]; then
+    echo "[Step 1] Check if the repository '$repo' is registered."
+    curl --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo"
 
     if [ $? -eq 0 ]; then
         echo
-        echo "Register succeed."
+        echo "[Step 1] Repository has already registered."
     else
         echo
-        echo "Register failed."
-        exit 1
+        echo "[Step 1] Repository isn't registered. Start registering with path '$register_path'"
+        curl --fail-with-body -X PUT "http://$es_host:$es_port/_snapshot/$repo" \
+            -H "Content-Type: application/json" \
+            -d "{\"type\":\"fs\",\"settings\":{\"location\":\"$register_path\"}}"
+
+        if [ $? -eq 0 ]; then
+            echo
+            echo "[Step 1] Register succeed."
+        else
+            echo
+            echo "[Step 1] Register failed."
+            exit 1
+        fi
     fi
 fi
 
 # Check if snapshot exists
-echo "Check if snapshot '$snapshot' exists."
-curl --silent --fail "http://$es_host:$es_port/_snapshot/$repo/$snapshot" > /dev/null
-
-if [ $? -eq 0 ]; then
-    echo "Snapshot '$snapshot' exists."
-else
-    echo "Snapshot '$snapshot' doesn't exist."
-    echo "Start creating snapshot."
-    curl --fail-with-body -X PUT "http://$es_host:$es_port/_snapshot/$repo/$snapshot" \
-        -H "Content-Type: application/json"
+if [ $from_step -le 2 ]; then
+    echo "[Step 2] Check if snapshot '$snapshot' exists."
+    curl --silent --fail "http://$es_host:$es_port/_snapshot/$repo/$snapshot" > /dev/null
 
     if [ $? -eq 0 ]; then
-        echo
-        echo "Creating snapshot succeed."
+        echo "[Step 2] Snapshot '$snapshot' exists."
     else
-        echo
-        echo "Creating snapshot failed."
-        exit 1
+        echo "[Step 2] Snapshot '$snapshot' doesn't exist."
+        echo "[Step 2] Start creating snapshot."
+        curl --fail-with-body -X PUT "http://$es_host:$es_port/_snapshot/$repo/$snapshot" \
+            -H "Content-Type: application/json"
+
+        if [ $? -eq 0 ]; then
+            echo
+            echo "[Step 2] Creating snapshot succeed."
+        else
+            echo
+            echo "[Step 2] Creating snapshot failed. You can retry from this step with option '--from-step 2'."
+            exit 1
+        fi
     fi
 fi
 
 # remove old files
-echo "Remove snapshot files at snapshot repository."
-docker exec -i $es_container rm -rf "$register_path/*"
+if [ $from_step -le 3 ]; then
+    echo "[Step 3] Remove snapshot files at snapshot repository."
+    docker exec -i $es_container rm -rf "$register_path/*"
 
-if [ $? -ne 0 ]; then
-    echo "Remove failed."
-    exit 1
+    if [ $? -ne 0 ]; then
+        echo "[Step 3] Remove failed. You can retry from this step with option '--from-step 3'."
+        exit 1
+    fi
 fi
 
 # copy files
-echo "Copy files from '$target' to snapshot repository folder."
-docker cp $target/. $es_container:$register_path/
+if [ $from_step -le 4 ]; then
+    echo "[Step 4] Copy files from '$target' to snapshot repository folder."
+    docker cp $target/. $es_container:$register_path/
 
-if [ $? -ne 0 ]; then
-    echo "Copy failed."
-    exit 1
+    if [ $? -ne 0 ]; then
+        echo "[Step 4] Copy failed. You can retry from this step with option '--from-step 4'."
+        exit 1
+    fi
 fi
 
 # modify ownership
-echo "Modify ownership of snapshot repository folder."
-docker exec -i $es_container chown -R elasticsearch:root $register_path
+if [ $from_step -le 5 ]; then
+    echo "[Step 5] Modify ownership of snapshot repository folder."
+    docker exec -i $es_container chown -R elasticsearch:root $register_path
 
-if [ $? -ne 0 ]; then
-    echo "Modify failed."
-    exit 1
+    if [ $? -ne 0 ]; then
+        echo "[Step 5] Modify failed. You can retry from this step with option '--from-step 5'."
+        exit 1
+    fi
 fi
 
 # restart
-echo "Restart elasticsearch..."
-docker restart $es_container
+if [ $from_step -le 6 ]; then
+    echo "[Step 6] Restart elasticsearch..."
+    docker restart $es_container
 
-if [ $? -ne 0 ]; then
-    echo "Restart failed."
-    exit 1
-fi
-
-is_es_start=false
-while ! $is_es_start; do
-    curl --silent --fail-with-body "http://$es_host:$es_port" > /dev/null
-    if [ $? -eq 0 ]; then
-        is_es_start=true
-        echo "ElasticSearch is running."
-    else
-        echo "Waiting for ElasticSearch service."
-        sleep 1
+    if [ $? -ne 0 ]; then
+        echo "[Step 6] Restart failed. You can retry from this step with option '--from-step 6'."
+        exit 1
     fi
-done
+
+    is_es_start=false
+    while ! $is_es_start; do
+        curl --silent --fail-with-body "http://$es_host:$es_port" > /dev/null
+        if [ $? -eq 0 ]; then
+            is_es_start=true
+            echo "[Step 6] ElasticSearch is running."
+        else
+            echo "[Step 6] Waiting for ElasticSearch service."
+            sleep 1
+        fi
+    done
+fi
 
 # get snapshot details
-echo "check if snapshot is loaded successfully."
-resp=$(curl --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo/$snapshot")
+if [ $from_step -le 7 ]; then
+    echo "[Step 7] check if snapshot is loaded successfully."
+    resp=$(curl --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo/$snapshot")
 
-if [ $? -ne 0 ]; then
-    echo "Getting snapshot details failed."
-    exit 1
-fi
+    if [ $? -ne 0 ]; then
+        echo "[Step 7] Getting snapshot details failed.  You can retry from this step with option '--from-step 7'."
+        echo "[Step 7] Error response:"
+        echo $resp
+        exit 1
+    fi
 
-if [ "$(echo $resp | grep $snapshot)" != "" ]; then
-    echo "Snapshot is loaded."
-else
-    echo "Snapshot doesn't exist."
-    exit 1
+    if [ "$(echo $resp | grep $snapshot)" != "" ]; then
+        echo "[Step 7] Snapshot is loaded."
+    else
+        echo "[Step 7] Snapshot doesn't exist. You can retry from this step with option '--from-step 7'."
+        exit 1
+    fi
 fi
 
 # restore
-echo "Start restoring."
+if [ $from_step -le 8 ]; then
+    echo "[Step 8] Start restoring."
 
-if [ "$index" == "" ]; then
-    curl --fail-with-body -X POST "http://$es_host:$es_port/_snapshot/$repo/$snapshot/_restore" \
-        -H "Content-Type: application/json"
-else
-    curl --fail-with-body -X POST "http://$es_host:$es_port/_snapshot/$repo/$snapshot/_restore" \
-        -H "Content-Type: application/json" \
-        -d "{\"indices\":[\"$index\"]}"
-fi
+    if [ "$index" == "" ]; then
+        curl --fail-with-body -X POST "http://$es_host:$es_port/_snapshot/$repo/$snapshot/_restore" \
+            -H "Content-Type: application/json"
+    else
+        curl --fail-with-body -X POST "http://$es_host:$es_port/_snapshot/$repo/$snapshot/_restore" \
+            -H "Content-Type: application/json" \
+            -d "{\"indices\":[\"$index\"]}"
+    fi
 
-if [ $? -ne 0 ]; then
-    echo
-    echo "Restore failed."
-    exit 1
+    if [ $? -ne 0 ]; then
+        echo
+        echo "[Step 8] Restore failed. You can retry from this step with option '--from-step 8'."
+        exit 1
+    fi
 fi
 
 echo "Done!!"
