#12 import: add unregister step; add default value to --repo and --snapshot; change --index to reuqired option

diff --git a/index-export b/index-export
--- a/index-export
+++ b/index-export
@@ -3,6 +3,7 @@
 # default value
 es_host=127.0.0.1
 es_port=9200
+repo=backup_repo
 es_container=elasticsearch
 register_path="/usr/share/elasticsearch/backup"
 from_step=1
@@ -56,11 +57,9 @@ while (($#)); do
         ;;
         "--help" | "-h")
             echo "Required options:"
-            echo "    --snapshot <snapshot>, -s <snapshot>"
-            echo "        Snapshot name."
-            echo "    --repo <repository>, -r <repository>"
-            echo "        Snapshot repository name."
-            echo
+            echo "    --index <index>, -i <index>"
+            echo "        Index that specified to be exported."
+            echo 
             echo "Optional options:"
             echo "    --eshost <host>, -eh <host>"
             echo "        Elasticsearch service host. Default: 127.0.0.1"
@@ -68,12 +67,14 @@ while (($#)); do
             echo "        Elasticsearch service port. Default: 9200"
             echo "    --escontainer <container name>, -ec <continer name>"
             echo "        Elasticsearch docker container name. Default: elasticsearch"
-            echo "    --index <index>, -i <index>"
-            echo "        Index that specified to be exported. Defaultly export all indices."
+            echo "    --repo <repository>, -r <repository>"
+            echo "        Snapshot repository name. Default: backup_repo"
+            echo "    --snapshot <snapshot>, -s <snapshot>"
+            echo "        Snapshot name. Default: snapshot_{index}"
             echo "    --register-path <path>, -rp <path>"
             echo "        Path of snapshot repository. Used for registering repository if repository doesn't exists. Default: /usr/share/elasticsearch/backup"
             echo "    --output <path>, -o <path>"
-            echo "        Output path. Defaultly use backup_{time} if index not specified, and use backup_{index} if index is specified."
+            echo "        Output path. Default: backup_{index}"
             echo "    --from-step <step>, -f <step>"
             echo "        Start from which step. Default: 1"
             exit 0
@@ -85,14 +86,13 @@ while (($#)); do
     esac
 done
 
-if [ "$repo" == "" ]; then
-    echo "Option --repo is required."
+if [ "$index" == "" ]; then
+    echo "--index is required."
     exit 1
 fi
 
-if [ "$snapshot" == "" ]; then
-    echo "Option --snapshot is required."
-    exit 1
+if [ "$snapshot" == "" ]; then    
+    snapshot="snapshot_$index"
 fi
 
 # checking repository register
@@ -139,7 +139,7 @@ if [ $from_step -le 2 ]; then
     fi
 fi
 
-# exporting index
+# creating snapshot
 if [ $from_step -le 3 ]; then
     if [ "$index" == "" ]; then
         echo
@@ -165,33 +165,42 @@ if [ $from_step -le 3 ]; then
     fi
 fi
 
-# Copy from docker container
+# unregister
 if [ $from_step -le 4 ]; then
+    echo "[Step 4] Unregister repository."
+    curl --fail-with-body -X DELETE "http://$es_host:$es_port/_snapshot/$repo"
+
+    if [ $? -ne 0 ]; then
+        echo
+        echo "[Step 4] Unregister failed. You can retry from this step with option '--from-step 4'."
+        exit 1
+    fi
+fi
+
+# Copy from docker container
+if [ $from_step -le 5 ]; then
     if [ "$output" == "" ]; then
-        if [ "$index" == "" ]; then
-            output="backup_$(date +"%Y%m%d-%H%M%S")"
-        else
-            output="backup_$index"
-        fi
+        output="backup_$index"
     fi
 
-    echo "[Step 4] Copy folder '$register_path' from docker continer '$es_container' to '$output'"
+    echo
+    echo "[Step 5] Copy folder '$register_path' from docker continer '$es_container' to '$output'"
     docker cp $es_container:$register_path ./$output
 
     if [ $? -ne 0 ]; then
-        echo "[Step 4] copied failed. You can retry from this step with option '--from-step 4'."
+        echo "[Step 5] copied failed. You can retry from this step with option '--from-step 5'."
         exit 1
     fi
 fi
 
 # delete snapshot
-if [ $from_step -le 5 ]; then
-    echo "[Step 5] Start deleting snapshot."
+if [ $from_step -le 6 ]; then
+    echo "[Step 6] Start deleting snapshot."
     curl --fail-with-body -X DELETE "http://$es_host:$es_port/_snapshot/$repo/$snapshot"
 
     if [ $? -ne 0 ]; then
         echo
-        echo "[Step 5] delete failed. You can retry from this step with option '--from-step 5'."
+        echo "[Step 6] delete failed. You can retry from this step with option '--from-step 6'."
         exit 1
     fi
 fi
