#24 add missing failure check

diff --git a/index-import b/index-import
--- a/index-import
+++ b/index-import
@@ -136,7 +136,6 @@ if [ $from_step -le 2 ]; then
             exit 1
         fi
     else
-        echo
         echo "[Step 2] Repository hasn't registered."
     fi
 fi
@@ -145,6 +144,13 @@ fi
 if [ $from_step -le 3 ]; then
     echo "[Step 3] Remove snapshot files at snapshot repository."
     docker exec -i $es_container rm -rf "$register_path"
+
+    if [ $? -eq 0 ]; then
+        echo "[Step 3] Remove succeed."
+    else
+        echo "[Step 3] Remove failed."
+        exit 1
+    fi
     docker exec -i $es_container mkdir "$register_path"
 fi
 
