#12 import: edit process

diff --git a/index-import b/index-import
--- a/index-import
+++ b/index-import
@@ -105,130 +105,105 @@ if [ "$index" == "" ]; then
     exit 1
 fi
 
-# checking repository register
+
+# remove existing repository
 if [ $from_step -le 1 ]; then
     echo "[Step 1] Check if the repository '$repo' is registered."
     curl --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo"
 
     if [ $? -eq 0 ]; then
         echo
-        echo "[Step 1] Repository has already registered."
+        echo "[Step 1] Repository has already registered. Unregister it."
+        curl -X DELETE --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo"
+        if [ $? -eq 0 ]; then
+            echo
+            echo "[Step 1] Unregister succeed."
+        else
+            echo
+            echo "[Step 1] Unregister failed."
+            exit 1
+        fi
     else
         echo
-        echo "[Step 1] Repository isn't registered. Start registering with path '$register_path'"
-        curl --fail-with-body -X PUT "http://$es_host:$es_port/_snapshot/$repo" \
-            -H "Content-Type: application/json" \
-            -d "{\"type\":\"fs\",\"settings\":{\"location\":\"$register_path\"}}"
-
-        if [ $? -eq 0 ]; then
-            echo
-            echo "[Step 1] Register succeed."
-        else
-            echo
-            echo "[Step 1] Register failed."
-            exit 1
-        fi
+        echo "[Step 1] Repository hasn't registered."
     fi
 fi
 
-# Check if snapshot exists
+# clean folder
 if [ $from_step -le 2 ]; then
-    echo "[Step 2] Check if snapshot '$snapshot' exists."
-    curl --silent --fail "http://$es_host:$es_port/_snapshot/$repo/$snapshot" > /dev/null
-
-    if [ $? -eq 0 ]; then
-        echo "[Step 2] Snapshot '$snapshot' exists."
-    else
-        echo "[Step 2] Snapshot '$snapshot' doesn't exist."
-        echo "[Step 2] Start creating snapshot."
-        curl --fail-with-body -X PUT "http://$es_host:$es_port/_snapshot/$repo/$snapshot?wait_for_completion=true" \
-            -H "Content-Type: application/json"
-
-        if [ $? -eq 0 ]; then
-            echo
-            echo "[Step 2] Creating snapshot succeed."
-        else
-            echo
-            echo "[Step 2] Creating snapshot failed. You can retry from this step with option '--from-step 2'."
-            exit 1
-        fi
-    fi
-fi
-
-# remove old files
-if [ $from_step -le 3 ]; then
-    echo "[Step 3] Remove snapshot files at snapshot repository."
+    echo "[Step 2] Remove snapshot files at snapshot repository."
     docker exec -i $es_container rm -rf "$register_path"
     docker exec -i $es_container mkdir "$register_path"
-
-    if [ $? -ne 0 ]; then
-        echo "[Step 3] Remove failed. You can retry from this step with option '--from-step 3'."
-        exit 1
-    fi
 fi
 
 # copy files
-if [ $from_step -le 4 ]; then
-    echo "[Step 4] Copy files from '$target' to snapshot repository folder."
+if [ $from_step -le 3 ]; then
+    echo "[Step 3] Copy files from '$target' to snapshot repository folder."
     docker cp $target/. $es_container:$register_path/
 
     if [ $? -ne 0 ]; then
-        echo "[Step 4] Copy failed. You can retry from this step with option '--from-step 4'."
+        echo "[Step 3] Copy failed. You can retry from this step with option '--from-step 3'."
         exit 1
     fi
 fi
 
 # modify ownership
-if [ $from_step -le 5 ]; then
-    echo "[Step 5] Modify ownership of snapshot repository folder."
+if [ $from_step -le 4 ]; then
+    echo "[Step 4] Modify ownership of snapshot repository folder."
     docker exec -i $es_container chown -R elasticsearch:root $register_path
 
     if [ $? -ne 0 ]; then
-        echo "[Step 5] Modify failed. You can retry from this step with option '--from-step 5'."
+        echo "[Step 4] Modify failed. You can retry from this step with option '--from-step 4'."
         exit 1
     fi
 fi
 
-# restart
-if [ $from_step -le 6 ]; then
-    echo "[Step 6] Restart elasticsearch..."
-    docker restart $es_container
-
-    if [ $? -ne 0 ]; then
-        echo "[Step 6] Restart failed. You can retry from this step with option '--from-step 6'."
+# register repository
+if [ $from_step -le 5 ]; then
+    echo "[Step 5] Check if repository has registered."
+    curl --fail-with-body -X PUT "http://$es_host:$es_port/_snapshot/$repo" \
+        -H "Content-Type: application/json" \
+        -d "{\"type\":\"fs\",\"settings\":{\"location\":\"$register_path\"}}"
+    
+    if [ $? -eq 0 ]; then
+        echo
+        echo "[Step 5] Register succeed."
+    else
+        echo
+        echo "[Step 5] Register failed. You can retry from this step with option '--from-step 5'."
         exit 1
     fi
-
-    is_es_start=false
-    while ! $is_es_start; do
-        curl --silent --fail-with-body "http://$es_host:$es_port" > /dev/null
-        if [ $? -eq 0 ]; then
-            is_es_start=true
-            echo "[Step 6] Elasticsearch is running."
-        else
-            echo "[Step 6] Waiting for Elasticsearch service."
-            sleep 1
-        fi
-    done
 fi
 
 # get snapshot details
-if [ $from_step -le 7 ]; then
-    echo "[Step 7] check if snapshot is loaded successfully."
+if [ $from_step -le 6 ]; then
+    echo "[Step 6] check if snapshot is loaded successfully."
     resp=$(curl --silent --fail-with-body "http://$es_host:$es_port/_snapshot/$repo/$snapshot")
 
     if [ $? -ne 0 ]; then
-        echo "[Step 7] Getting snapshot details failed.  You can retry from this step with option '--from-step 7', or restart Elasticsearch again with option '--from-step 6'."
-        echo "[Step 7] Error response:"
+        echo "[Step 6] Getting snapshot details failed.  You can retry from this step with option '--from-step 6'."
+        echo "[Step 6] Error response:"
         echo $resp
         exit 1
     fi
 
     if [ "$(echo $resp | grep $snapshot)" != "" ]; then
-        echo "[Step 7] Snapshot is loaded."
+        echo "[Step 6] Snapshot is loaded."
     else
-        echo "[Step 7] Snapshot doesn't exist. You can retry from this step with option '--from-step 7', or restart Elasticsearch again with option '--from-step 6'."
+        echo "[Step 6] Snapshot doesn't exist. You can retry from this step with option '--from-step 6'."
         exit 1
+    fi
+fi
+
+# check if the index exists.
+if [ $from_step -le 7 ]; then
+    echo "[Step 7] Check if the index exists."
+    resp=$(curl --silent --fail-with-body "http://$es_host:$es_port/_cat/indices/$index")
+
+    if [ "$(echo $resp | grep " $index ")" != "" ]; then
+        echo "[Step 7] Index '$index' exists. You can remove it by 'DELETE http://$es_host:$es_port/$index' and retry from this step with option '--from-step 7'."
+    else
+        echo "[Step 7] Index '$index' doesn't exist."
     fi
 fi
 
@@ -247,7 +222,7 @@ if [ $from_step -le 8 ]; then
 
     if [ $? -ne 0 ]; then
         echo
-        echo "[Step 8] Restore failed. You can retry from this step with option '--from-step 8', or restart Elasticsearch again with option '--from-step 6'."
+        echo "[Step 8] Restore failed. You can retry from this step with option '--from-step 8'."
         exit 1
     fi
 fi
